sudo: disable
language: gcc
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
  - sudo apt-get update
  - sudo apt-get install -y libavutil-dev libavcodec-dev libavformat-dev libmaxminddb-dev
#  - sudo apt-get install -y --no-install-recommends --no-install-suggests graphicsmagick-libmagick-dev-compat libgraphicsmagick++1-dev libwebp-dev libmaxminddb-dev libmysqlclient-dev libssl-dev libcurl4-openssl-dev pkg-config

addons:
  apt:
    packages:
      - graphicsmagick-libmagick-dev-compat
      - libgraphicsmagick++-dev
      - libwebp-dev
#      - libmaxminddb-dev

script:
  - mkdir build && cd build && cmake .. && make && ctest