sudo: disable
language: cpp
dist: xenial

before_install:
#  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
#  - sudo apt-get update
#  - sudo apt show libmaxminddb-dev
#  - sudo apt-get install -y libmaxminddb-dev
#  - sudo apt-get install -y libavutil-dev libavcodec-dev libavformat-dev libmaxminddb-dev
#  - sudo apt-get install -y --no-install-recommends --no-install-suggests graphicsmagick-libmagick-dev-compat libgraphicsmagick++-dev libwebp-dev libmaxminddb-dev libmysqlclient-dev libssl-dev libcurl4-openssl-dev pkg-config
  - Magick-config --version
  - Magick-config --cppflags
  - Magick-config --ldflags
  - Magick-config --libs
  - Magick++-config --version
  - Magick++-config --cppflags
  - Magick++-config --ldflags
  - Magick++-config --libs

addons:
  apt:
    update: true
    packages:
      - graphicsmagick-libmagick-dev-compat
      - libgraphicsmagick++-dev
      - libwebp-dev
      - libmaxminddb-dev

script:
  - mkdir build && cd build && cmake .. && make && ctest