sudo: false
language: c++

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
  - sudo apt-get update -q
 
addons:
  apt:
    packages:
      - graphicsmagick-libmagick-dev-compat
      - libgraphicsmagick++1-dev
      - libwebp-dev

script:
  - mkdir build && cd build && cmake .. && make
  - ctest