sudo: false
language: c++

addons:
  apt:
    packages:
      - graphicsmagick-libmagick-dev-compat
      - libgraphicsmagick++1-dev
      - libwebp-dev

script:
  - mkdir build && cd build && cmake .. && make
  - ctest